inputs_def:
  - handle: online_url
    description: Input
    json_schema:
      contentMediaType: oomol/var
      type: string
    value: ""
  - handle: name
    json_schema:
      contentMediaType: oomol/var
      type: string
  - handle: local_folder
    json_schema:
      contentMediaType: oomol/var
      type: string
      ui:widget: dir
outputs_def:
  - handle: file_address
    description: Output
    json_schema:
      type: string
icon: ":skill-icons:typescript:"
ui:
  default_width: 530
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
